### ISSUE TITLE
Question 12 - n paths of length 3

### ISSUE THREAD

**Issue by swouf** [swouf/ntds_IMDb_team4#2]
La question est :

>How many paths of length 3 are there in your graph? Hint: calling the `compute_paths` function on every pair of node is not an efficient way to do it.

Il faut écrire un petit code pour ça. Les questions 10 et 11 ont déjà été répondue. J'ai pas trop d'idée pour le moment, je reprendrai ça demain (21/10/2018) après-midi.

**Comment by swouf** [comment]
J'ai trouvé !

**Question 12**

*Code :* `print(np.sum(np.linalg.matrix_power(adjacency,3)))`

*Out :* `28760500552`

**Comment by hanaSam** [comment]
Trop bien! Tu gères
